### ISSUE TITLE
Can't publish project to Hubs

### ISSUE THREAD

**Issue by TuxMiester** [mozilla/Spoke#1252]
It shows 
"cannot read properties of null (reading 'animations').
How do I fix this ?

**Comment by jywarren** [comment]
I also just got this error - "cannot read properties of null (reading 'array')" - 

<img width="452" alt="image" src="https://github.com/mozilla/Spoke/assets/24359/ef144509-9e18-41f1-9c6e-d321645e6bf8">

JS error was:

```
EditorContainer.js:862 TypeError: Cannot read properties of null (reading 'array')
    at dt._combine (MeshCombinationGroup.js:223:50)
    at dt.combineMeshes (MeshCombinationGroup.js:151:34)
    at async Lt.combineMeshes (SceneNode.js:416:3)
    at async Pa.exportScene (Editor.js:384:9)
    at async ne.publishProject (Api.js:806:24)
    at async EditorContainer.js:843:7
```

**Comment by jywarren** [comment]
I was able to resolve this by deleting one object (an image) from the scene that I had recently added. Then i re-added it and unchecked "combine" since i thought MeshCombinationGroup.js was a clue. That worked.
