### ISSUE TITLE
Error publishing simple room to hubs

### ISSUE THREAD

**Issue by claudkrog** [mozilla/Spoke#1282]
![hubs-error](https://github.com/mozilla/Spoke/assets/25188182/3b8236ce-da5a-4d25-8b61-d8f15b6217b5)

**Comment by mikemorran** [comment]
We are seeing this issue more and more from users attempting to publish projects on hubs.mozilla.com/spoke. Triage needed

**Comment by jywarren** [comment]
Also just saw this, but waited a few minutes and it went away. Here is the JS log:

```

/api/v1/meta:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
EditorContainer.js:673 o: Failed to fetch "https://hubs.mozilla.com/api/v1/meta":
  Cause:
    Failed to fetch (Possibly a CORS error)
    at ne.fetch (https://hmc-assets.reticulum.io/spoke/assets/js/entry-461bec5998bf488f9075.js:2:191512)
    at async ne.upload (https://hmc-assets.reticulum.io/spoke/assets/js/entry-461bec5998bf488f9075.js:2:188120)
    at async ne.saveProject (https://hmc-assets.reticulum.io/spoke/assets/js/entry-461bec5998bf488f9075.js:2:181723)
    at async Pa.<anonymous> (https://hmc-assets.reticulum.io/spoke/assets/js/project-page-bdc269b40a0cdc427c4a.js:1:478461)
TypeError: Failed to fetch (Possibly a CORS error)
    at ne.fetch (https://hmc-assets.reticulum.io/spoke/assets/js/entry-461bec5998bf488f9075.js:2:191239)
    at ne.upload (https://hmc-assets.reticulum.io/spoke/assets/js/entry-461bec5998bf488f9075.js:2:188131)
    at ne.saveProject (https://hmc-assets.reticulum.io/spoke/assets/js/entry-461bec5998bf488f9075.js:2:181734)
    at async Pa.<anonymous> (https://hmc-assets.reticulum.io/spoke/assets/js/project-page-bdc269b40a0cdc427c4a.js:1:478461)
```
