### ISSUE TITLE
Video not working

### ISSUE THREAD

**Issue by antiantivirus** [mozilla/Spoke#964]
When loading in a video from an external source i get the following error. Assuming its an issue with the video codec.

VideoNode.js:139 o: Error loading video https://www.youtube.com/watch?v=6Le68Sd-WMo:
  Cause:
    Error loading video "https://hubs-proxy.com/https://www.youtube.com/watch?v=6Le68Sd-WMo":
      Cause:
        DEMUXER_ERROR_COULD_NOT_OPEN: FFmpegDemuxer: open context failed
    at Wi.load (https://assets-prod.reticulum.io/spoke/assets/js/project-page-ab50b779eac100e2f27d.js:1:132441)
o: Error loading video "https://hubs-proxy.com/https://www.youtube.com/watch?v=6Le68Sd-WMo":
  Cause:
    DEMUXER_ERROR_COULD_NOT_OPEN: FFmpegDemuxer: open context failed
    at HTMLVideoElement.s (https://assets-prod.reticulum.io/spoke/assets/js/project-page-ab50b779eac100e2f27d.js:1:129493)
    at HTMLVideoElement.r (https://assets-prod.reticulum.io/spoke/assets/js/entry-59eaae05a6c267888ef3.js:2:539753)
undefined

**Comment by antiantivirus** [comment]
Any advice, possible fix? Still getting this error.

**Comment by brunomartelli** [comment]
if a vimeo video has no sound it will play

**Comment by antiantivirus** [comment]
OK  thanks, good tip for getting round this issue whilst its not working quite correctly at the moment.

**Comment by emclaren** [comment]
screencaps of how vimeo videos appear with/without sound when I try to load them into Spoke & Hubs. Obscured them a bit because they came from community member and I wasn't sure if they would be ok with them being shared.

Spoke (the one with no sound appears as video, the one with sound appears as link)
<img width="1514" alt="Screen Shot 2020-09-01 at 10 46 27 AM" src="https://user-images.githubusercontent.com/6835324/91888552-59b0a680-ec41-11ea-8ccb-f6f0842b8029.png">

Hubs (both appear)
<img width="1370" alt="Screen Shot 2020-09-01 at 10 46 17 AM" src="https://user-images.githubusercontent.com/6835324/91888631-79e06580-ec41-11ea-94b1-1ed3fcd99d94.png">

**Comment by emclaren** [comment]
This was also being discussed on the github discussions board for hubs: https://github.com/mozilla/hubs/discussions/2859

**Comment by oli414** [comment]
When looking at the network response for the video I see the following:
 `<?xml version='1.0' encoding='UTF-8'?><Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.</Message><StringToSign>GET`

**Comment by BonzoMartini** [comment]
I have found that hosting my videos on my pro Vimeo account works like crap, hosting my videos on Youtube works fine and unlike Vimeo vids you get an image preview in Spoke. (and more videos play) - BUT my Hubs are on AWS

**Comment by oli414** [comment]
Alright sounds promosing I'll give YouTube another shot then. Did you have to change anything about the content-security policy on your admin panel?

**Comment by BonzoMartini** [comment]
..errm i dont think so. I set my youtube vids to unlisted
